apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crud-api
  labels:
    cloud.googleapis.com/location: __GCP_REGION__
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cloudsql-instances: __INSTANCE_CONNECTION_NAME__
        run.googleapis.com/client-name: cloud-console
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: crud-api
        image: __DOCKERHUB_USERNAME__/crud-api:__VERSION__
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://127.0.0.1:3306/__DB_NAME__"
        - name: SPRING_DATASOURCE_USERNAME
          value: "__DB_USER__"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "__DB_PASSWORD__"
        - name: LOKI_URL
          value: "__LOKI_URL__"
        - name: ENVIRONMENT
          value: "production"
        resources:
          limits:
            cpu: '2'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
